services:
    app:
        image: johnkristan/jarvis-designs:latest
        container_name: jarvis_designs_api_server
        restart: always
        ports:
            - "9000:9000"
        env_file:
            - .env
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/live/expenseproapi.notenexus.it.com:/etc/letsencrypt/live/expenseproapi.notenexus.it.com:ro
            - /etc/letsencrypt/archive/expenseproapi.notenexus.it.com:/etc/letsencrypt/archive/expenseproapi.notenexus.it.com:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
