name: Dependabot CI

on:
  pull_request:

jobs:
  server:
    if: contains(github.event.pull_request.title, 'composer')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd server && composer install
      - run: cd server && php artisan test

  client:
    if: contains(github.event.pull_request.title, 'npm')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client && npm install
      - run: cd client && npm run build